from app import app, db
from models import CarHitbox

CAR_HITBOXES = {
    # BREAKOUT
    "1966 Cadillac DeVille": "Breakout",
    "Ace": "Breakout",
    "Animus GP": "Breakout",
    "Azura": "Breakout",
    "Breakout": "Breakout",
    "Breakout Type-S": "Breakout",
    "Breakout X": "Breakout",
    "Cyberpunk Quadra": "Breakout",
    "Cyclone": "Breakout",
    "Diesel": "Breakout",
    "Emperor": "Breakout",
    "Emperor II": "Breakout",
    "Ferrari F40": "Breakout",
    "Fast and Furious Mazda RX7": "Breakout",
    "Fuse": "Breakout",
    "Chevrolet Corvette Stingray": "Breakout",
    "Chevrolet Corvette ZR1": "Breakout",
    "Komodo": "Breakout",
    "Mako": "Breakout",
    "McLaren Senna": "Breakout",
    "Megastar": "Breakout",
    "Nexus": "Breakout",
    "Nexus SC": "Breakout",
    "Pontiac Firebird": "Breakout",
    "Porsche 918 Spyder": "Breakout",
    "Redline": "Breakout",
    "Revolver": "Breakout",
    "Samurai": "Breakout",
    "The Incredibile": "Breakout",
    "Whiplash": "Breakout",

    # DOMINUS
    "89 Batmobile": "Dominus",
    "007 Aston Martin DBS": "Dominus",
    "007 Aston Martin Valhalla": "Dominus",
    "Admiral": "Dominus",
    "Aftershock": "Dominus",
    "Batmobile (2022)": "Dominus",
    "Bumblebee Car": "Dominus",
    "BMW M3 E30": "Dominus",
    "BMW M4 GT3 EVO": "Dominus",
    "BMW M240i": "Dominus",
    "Chikara": "Dominus",
    "Chikara G1": "Dominus",
    "Chikara GXT": "Dominus",
    "DeLorean Time Machine": "Dominus",
    "Diestro": "Dominus",
    "Dodge Charger Daytona Scat Pack": "Dominus",
    "Dominus": "Dominus",
    "Dominus GT": "Dominus",
    "Ecto-1": "Dominus",
    "Fast and Furious Dodge Charger": "Dominus",
    "Fast and Furious Dodge Charger SRT Hellcat": "Dominus",
    "Ferrari 296 GTB": "Dominus",
    "Ford Mustang Shelby GT350R": "Dominus",
    "Ford Mustang GTD": "Dominus",
    "Gazella GT": "Dominus",
    "Guardian": "Dominus",
    "Guardian G1": "Dominus",
    "Guardian GXT": "Dominus",
    "Homer's Car": "Dominus",
    "Hotshot": "Dominus",
    "Ice Charger": "Dominus",
    "Imperator DT5": "Dominus",
    "KITT Knight Rider": "Dominus",
    "Lamborghini Countach LPI 800-4": "Dominus",
    "Lamborghini Huracan STO": "Dominus",
    "Lightning McQueen": "Dominus",
    "Lockjaw": "Dominus",
    "Maestro": "Dominus",
    "Magnifique": "Dominus",
    "Magnifique GXT": "Dominus",
    "Mamba": "Dominus",
    "Masamune": "Dominus",
    "Maverick": "Dominus",
    "Maverick G1": "Dominus",
    "Maverick GXT": "Dominus",
    "McLaren 570S": "Dominus",
    "McLaren 765LT": "Dominus",
    "McLaren P1": "Dominus",
    "Mercedes-AMG GT 63 S": "Dominus",
    "Mercedes-Benz CLA": "Dominus",
    "MR11": "Dominus",
    "NASCAR Chevrolet Camaro": "Dominus",
    "NASCAR Ford Mustang": "Dominus",
    "NASCAR Toyota Camry": "Dominus",
    "NASCAR Next Gen Chevrolet Camaro": "Dominus",
    "NASCAR Next Gen Ford Mustang": "Dominus",
    "NASCAR Next Gen Toyota Camry": "Dominus",
    "Nemesis": "Dominus",
    "Nissan Fairlady Z": "Dominus",
    "Nissan Z Performance Car": "Dominus",
    "Peregrine TT": "Dominus",
    "Porsche 911 GT3 RS": "Dominus",
    "Porsche 911 Turbo": "Dominus",
    "Ripper": "Dominus",
    "Ronin": "Dominus",
    "Ronin G1": "Dominus",
    "Ronin GXT": "Dominus",
    "Samus Gunship": "Dominus",
    "Scorpion": "Dominus",
    "Tyranno": "Dominus",
    "Tyranno GXT": "Dominus",
    "Werewolf": "Dominus",

    # HYBRID
    "Beskar": "Hybrid",
    "Endo": "Hybrid",
    "Esper": "Hybrid",
    "Fast and Furious Nissan Skyline": "Hybrid",
    "Fast and Furious Pontiac Fiero": "Hybrid",
    "Hearse": "Hybrid",
    "Insidio": "Hybrid",
    "Jager 619": "Hybrid",
    "Lamborghini Urus": "Hybrid",
    "Nimbus": "Hybrid",
    "Nissan Silvia": "Hybrid",
    "Nissan Skyline GT-R R32": "Hybrid",
    "Primo": "Hybrid",
    "R3MX": "Hybrid",
    "R3MX GXT": "Hybrid",
    "RAM 1500 RHO": "Hybrid",
    "Tesla Cybertruck": "Hybrid",
    "Tygris": "Hybrid",
    "Venom": "Hybrid",
    "Void Burn": "Hybrid",
    "X-Devil": "Hybrid",
    "X-Devil MK2": "Hybrid",

    # MERC
    "Battle Bus": "Merc",
    "Behemoth": "Merc",
    "Chevrolet Astro": "Merc",
    "Defender D7X-R": "Merc",
    "Ford Bronco Raptor": "Merc",
    "Merc": "Merc",
    "The Mystery Machine": "Merc",
    "Nomad": "Merc",
    "Nomad GXT": "Merc",
    "Recoil AV": "Merc",
    "Stampede": "Merc",
    "Turtle Van": "Merc",

    # OCTANE
    "007 Aston Martin DB5": "Octane",
    "Armadillo": "Octane",
    "Backfire": "Octane",
    "BMW 1 Series": "Octane",
    "Bone Shaker": "Octane",
    "Corlay": "Octane",
    "Dingo": "Octane",
    "Fast 4WD": "Octane",
    "Fennec": "Octane",
    "Fennec ZR-F": "Octane",
    "Ford F-150": "Octane",
    "Ford Mustang Mach-E": "Octane",
    "Gizmo": "Octane",
    "Grog": "Octane",
    "Harbinger": "Octane",
    "Harbinger GXT": "Octane",
    "Hogsticker": "Octane",
    "Honda Civic Type R": "Octane",
    "Jackal": "Octane",
    "Jurassic Jeep Wrangler": "Octane",
    "Jeep Wrangler Rubicon": "Octane",
    "Marauder": "Octane",
    "Mario NSR": "Octane",
    "Luigi NSR": "Octane",
    "Mudcat": "Octane",
    "Mudcat G1": "Octane",
    "Mudcat GXT": "Octane",
    "Octane": "Octane",
    "Octane ZSR": "Octane",
    "Outlaw": "Octane",
    "Outlaw GXT": "Octane",
    "Patty Wagon": "Octane",
    "Proteus": "Octane",
    "Road Hog": "Octane",
    "Road Hog XL": "Octane",
    "Scarab": "Octane",
    "Shokunin": "Octane",
    "Shokunin GXT": "Octane",
    "Sweet Tooth": "Octane",
    "Takumi": "Octane",
    "Takumi RX-T": "Octane",
    "Triton": "Octane",
    "The Dark Knight Tumbler": "Octane",
    "Twinzer": "Octane",
    "Volkswagen Golf GTI": "Octane",
    "Vulcan": "Octane",
    "Xentari": "Octane",
    "Zippy": "Octane",

    # PLANK
    "16 Batmobile": "Plank",
    "Bugatti Centodieci": "Plank",
    "Artemis": "Plank",
    "Artemis G1": "Plank",
    "Artemis GXT": "Plank",
    "Centio": "Plank",
    "Formula 1 2021": "Plank",
    "Formula 1 2022": "Plank",
    "Mantis": "Plank",
    "Paladin": "Plank",
    "Sentinel": "Plank",
    "Twin Mill III": "Plank",
}

with app.app_context():
    db.create_all()
    count = 0
    for car, hitbox in CAR_HITBOXES.items():
        existing = CarHitbox.query.filter_by(car_name=car).first()
        if not existing:
            db.session.add(CarHitbox(car_name=car, hitbox_class=hitbox))
            count += 1
    db.session.commit()
    print(f"Seeded {count} cars successfully!")
    print(f"Total cars in DB: {CarHitbox.query.count()}")